server:
  port: 8181
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?useSSL=false
    username: root
    password: root
    name: myds
    
  jpa:
    show-sql: true
